---
- hosts: myhosts
  become: yes
  tasks:
  - name: install tree on servers
    apt:
     name: tree
     state: present
  tasks:
  - name: install wget on both
    apt: 
      name: wget
      state: present